name: empty_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  shared_widgets:
    path: packages/shared_widgets
  shared_constants:
    path: packages/shared_constants

  # Databases
  firebase_firestore_remote_database:
    path: packages/firebase_firestore_remote_database

  # Repos
  user_repository:
    path: packages/user_repository

  # Animations
  animations: ^2.0.11
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  # Dependency Injection
  get_it: ^7.6.7

  # Dart
  fpdart: ^1.1.0
  # Image
  cached_network_image: ^3.3.1
  # Router
  go_router: ^13.1.0
  # JSON
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  # Logging
  logging: ^1.2.0
  # Widget
  skeletonizer: ^1.0.1
  # Firebase
  firebase_core: ^2.30.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0

  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
