name: empty_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  preferences_api:
    path: packages/preferences_api
  preferences_api_shared:
    path: packages/preferences_api_shared
  shared_widgets:
    path: packages/shared_widgets
  shared_constants:
    path: packages/shared_constants
  user_api:
    path: packages/user_api
  user_api_firebase:
    path: packages/user_api_firebase
  permission_service_api:
    path: packages/permission_service_api
  permission_service_api_handler:
    path: packages/permission_service_api_handler
  image_service_api:
    path: packages/image_service_api
  image_service_api_picker:
    path: packages/image_service_api_picker
  location_service_api:
    path: packages/location_service_api
  location_service_api_geolocator:
    path: packages/location_service_api_geolocator

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  # Dependency Injection
  get_it: ^7.6.7

  # Dart
  fpdart: ^1.1.0
  # Router
  go_router: ^13.1.0
  # JSON
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  # Logging
  logging: ^1.2.0

  
  # Widget
  skeletonizer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0

  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
