name: image_service_api_picker
description: description
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

  image_service_api:
    path: ../image_service_api

  # Annotations
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Image Picker
  image_picker: ^1.0.7

dev_dependencies:
  very_good_analysis: ^5.1.0
  mocktail: ^1.0.0
  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1